# Generated by Django 4.0 on 2022-10-12 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='outlet',
        ),
        migrations.AddField(
            model_name='companies',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='payment_method',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='companies',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.branch'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.companies'),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='volunteers.branch'),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='phone',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
