# Generated by Django 4.0 on 2022-10-13 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_remove_delivery_outlet_companies_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='followUp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='companies',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='volunteers.branch'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='volunteers.companies'),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='volunteers.branch'),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
